apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-gateway
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: cloud-run-sa@smartwatts-staging.iam.gserviceaccount.com
      containers:
      - image: europe-west1-docker.pkg.dev/smartwatts-staging/api-gateway/api-gateway:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "cloudrun"

        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 15

