apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: edge-gateway
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        edge.rs485.configVersion: "20251118145122"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: cloud-run-sa@smartwatts-staging.iam.gserviceaccount.com
      containers:
      - image: europe-west1-docker.pkg.dev/smartwatts-staging/edge-gateway/edge-gateway:latest
        ports:
        - name: http1
          containerPort: 8088
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{"edge":{"rs485":{"enabled":true,"defaultPort":"/dev/ttyS0","defaultBaudRate":9600,"defaultDataBits":8,"defaultParity":"NONE","defaultStopBits":1,"readTimeout":1000,"writeTimeout":1000,"pollingInterval":5000,"autoDiscovery":false,"enableLogging":false}}}'
        - name: SPRING_PROFILES_ACTIVE
          value: "cloudrun"
        - name: SPRING_MAIN_ALLOW-BEAN-DEFINITION-OVERRIDING
          value: "true"
        - name: SERVER_PORT
          value: "8088"

        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "https://service-discovery-3daykcsw5a-ew.a.run.app/eureka/"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 15

