apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: notification-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: cloud-run-sa@smartwatts-staging.iam.gserviceaccount.com
      containers:
      - image: europe-west1-docker.pkg.dev/smartwatts-staging/notification-service/notification-service:latest
        ports:
        - name: http1
          containerPort: 8093
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "cloudrun"
        - name: SERVER_PORT
          value: "8093"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "https://service-discovery-3daykcsw5a-ew.a.run.app/eureka/"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: latest
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8093
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 15

