apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: service-discovery
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: cloud-run-sa@smartwatts-staging.iam.gserviceaccount.com
      containers:
      - image: europe-west1-docker.pkg.dev/smartwatts-staging/service-discovery/service-discovery:latest
        ports:
        - name: http1
          containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "cloudrun"

        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "https://service-discovery-3daykcsw5a-ew.a.run.app/eureka/"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0"
            memory: "256Mi"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

